[Feature] Add option to set 'obsolete'-tag to private torrents that are not needed but kept anyway.
ManiMatter/decluttarr pull request #194
Opened 2024-11-24 12:10 UTC by Dark3clipse

**Description**
This feature introduces an option to tag torrents in qBittorrent that are determined to no longer be needed by the *arrs. This allows third-party tools to remove these torrents at a later stage when seeding requirements are met.

**Use case**
You have private trackers and want to make sure that you meet the seeding requirements before removing these torrents. Sometimes, torrents are no longer needed by the *arrs. You would like to remove these torrents after the seeding requirements are met. A tool like [qbit_manage](https://github.com/StuffAnThings/qbit_manage) can do this for you.

However, such tools would need to know which torrents are no longer needed (obsolete) by the *arrs. By making decluttarr tag these torrents, third party tools such as qbit_manage can be used to cleanup these torrents after seeding requirements are met.

**Changes**
- Add new option 'OBSOLETE_QBIT_TAG' to the configuration.
- Create a description for the new option in the readme.
- Add function to create the tag in qBittorrent if it doesn't exist yet.
- Add logic in shared.py to set the tag using a post request.

2024-12-08 12:24 UTC, ManiMatter commented
hi @Dark3clipse, thanks for your contribution.

The behavior is not entirely clear to me, here are a few thoughts.
1) Could you please take care of the merge conflicts / rebase to the dev-branch commit
2) I would expect that a boolean variable enables/disables this behavior, not the tag itself
3) The tag should only be created if the feature is being used in qbit
4) Readme is not self explanatory for me, if you maybe could take care of 2) and 3) and the update the readme, that'd be appreciated

2024-12-20 00:07 UTC, Dark3clipse commented
Thank you for the feedback, I will rework the code.

2024-12-20 12:58 UTC, Dark3clipse commented
It is not clear to me what you mean with:
3. The tag should only be created if the feature is being used in qbit

We have no knowledge of what other tools are managing/using qbit (such as qbitmanage). Also, I think decluttarr should not have to know. You just set the feature to True if you want to use it imo. qbit itself is not 'using' the tags. 

I do check the existence of the tag in qbittorrent (see loadScripts.py) and create it if the feature is enabled and the tag string is not empty.

2024-12-20 13:11 UTC, Dark3clipse commented
Except for your 3rd point, the code should be reworked now. Could you have another look to see if your concerns have been addressed? Thank you :)

2024-12-21 13:04 UTC, ManiMatter requested changes
Hey!

Almost there I think. 

Please can you have a look at my comments. 
Also, I saw the unit tests failed in the github actions, pls can you check?

2024-12-21 13:04 UTC, ManiMatter commented on src/utils/loadScripts.py
> +        if settingsDict['SET_OBSOLETE_QBIT_TAG'] and settingsDict['OBSOLETE_QBIT_TAG']:
`and settingsDict['OBSOLETE_QBIT_TAG']:`

isn't that check redundant? this value will always be true, since you are setting a default in the definitions.py?

2024-12-21 13:04 UTC, ManiMatter commented on README.md
> +- Note: the tag can be used by third-party tools to remove these torrents after required seeding time has passed.
Note: the tag can be used by third-party tools (such as [qbit_manage](https://github.com/StuffAnThings/qbit_manage))to remove these torrents after required seeding time has passed.

would it make sense to add qbit_manage as example?

2024-12-21 13:04 UTC, ManiMatter commented on README.md
> +- The tag can be used by third-party tools to remove these torrents after required seeding time has passed.
The tag can be used by third-party tools (such as [qbit_manage](https://github.com/StuffAnThings/qbit_manage)) to remove these torrents after required seeding time has passed.

would it make sense to add qbit_manage as example?

2024-12-21 13:04 UTC, ManiMatter commented on README.md
> +- Set a tag on torrents in qBittorrent that can be removed, but are kept because they are private torrents.
- If this feature is turned on, private torrents in qBittorrent are not removed once the conditions for removal are met; instead, they are tagged with the obsolete-tag

I would formulate it like this - if you are OK

2024-12-21 13:04 UTC, ManiMatter commented on main.py
> +    await createQbitObsoleteTag(settingsDict)
_3. The tag should only be created if the feature is being used in qbit_

My point was referring to this line. In my mind you should only create a obsolete tag in qbit if this feature is even used.
```
if settingsDict['SET_OBSOLETE_QBIT_TAG']
     await createQbitObsoleteTag(settingsDict)
```

2024-12-21 13:04 UTC, ManiMatter commented on src/utils/loadScripts.py
> +    logger.info('%s | Setting obsolete tag on private torrents that are due for removal (%s)', str(settingsDict['SET_OBSOLETE_QBIT_TAG']), 'SET_OBSOLETE_QBIT_TAG')
logger.info("%s | Keeping private torrents in qBit due for removal and tagging instead (tag: '%s')", str(settingsDict['SET_OBSOLETE_QBIT_TAG']), 'SET_OBSOLETE_QBIT_TAG')

Proposal above.

2024-12-21 13:04 UTC, ManiMatter commented on src/utils/shared.py
> +            if settingsDict['SET_OBSOLETE_QBIT_TAG'] and settingsDict['OBSOLETE_QBIT_TAG']:
settingsDict['OBSOLETE_QBIT_TAG'] - same as above. isnt this obsolete due to default value?

2024-12-21 13:04 UTC, ManiMatter commented on src/utils/shared.py
> +                    ">>> Removing %s download (without removing from torrent client but with setting obsolete tag): %s",
">>> Removing %s download (keeping it in torrent client and adding tag '%s'

where %s is settingsDict['OBSOLETE_QBIT_TAG'] 


proposal above.

2024-12-21 13:04 UTC, ManiMatter commented on src/utils/shared.py
> +            if not removeFromClient and settingsDict['QBITTORRENT_URL'] and settingsDict['SET_OBSOLETE_QBIT_TAG'] and settingsDict['OBSOLETE_QBIT_TAG'] and affectedItem["downloadId"]:
settingsDict['OBSOLETE_QBIT_TAG']  -> redundant?

2024-12-23 22:33 UTC, Dark3clipse commented
I'll need some time due to Christmas with in laws, I will come back and address the remaining work in a couple of days if that's okay. Again, thank you a lot for the feedback. Let's make this feature solid :) Wish you a nice holiday season as well.

2025-01-18 19:37 UTC, Dark3clipse commented on src/utils/loadScripts.py
> +        if settingsDict['SET_OBSOLETE_QBIT_TAG'] and settingsDict['OBSOLETE_QBIT_TAG']:
removed the check

2025-01-18 19:38 UTC, Dark3clipse commented on README.md
> +- Note: the tag can be used by third-party tools to remove these torrents after required seeding time has passed.
changed

2025-01-18 19:38 UTC, Dark3clipse commented on README.md
> +- Set a tag on torrents in qBittorrent that can be removed, but are kept because they are private torrents.
changed

2025-01-18 19:40 UTC, Dark3clipse commented on src/utils/shared.py
> +            if settingsDict['SET_OBSOLETE_QBIT_TAG'] and settingsDict['OBSOLETE_QBIT_TAG']:
it is, removed

2025-01-18 19:56 UTC, Dark3clipse commented
I've resolved the issues and applied your requested changes. Let me know what you think. Apologies for the delay, it has been a busy time for me. Also I've made sure the tests are passing now.

2025-04-18 22:59 UTC, ManiMatter commented
hi @Dark3clipse , apologies for the radio silence on my part.

I've been refactoring the entire application, and it took me way longer than I hoped.
Goal was to make it more maintainable, and also support multiple instances and some of the features people have been requesting - such as the obsolete tag of yours.

It's still in draft, and particularly the readme I still have to write (and I'm sure there's plenty of bugs).
But if you have any feedback / suggestions, I'd be happy to hear and also contributions are highly welcome:

Branch is here: https://github.com/ManiMatter/decluttarr/tree/decluttarr-v2

2025-04-19 16:17 UTC, Dark3clipse commented
Hi @ManiMatter!

Good to hear from you. I'll gladly review the refactoring. Also, what do you want to do with this PR? I guess we will need to rebase it after the refactoring?

Sent from Proton Mail Android

-------- Original Message --------
On 19/04/2025 00:59, ManiMatter wrote:
hi @Dark3clipse , apologies for the radio silence on my part.
I've been refactoring the entire application, and it took me way longer than I hoped.
Goal was to make it more maintainable, and also support multiple instances and some of the features people have been requesting - such as the obsolete tag of yours.
It's still in draft, and particularly the readme I still have to write (and I'm sure there's plenty of bugs).
But if you have any feedback / suggestions, I'd be happy to hear and also contributions are highly welcome:
Branch is here: https://github.com/ManiMatter/decluttarr/tree/decluttarr-v2
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.￼Message ID: ***@***.***>
￼ManiMatter left a comment (ManiMatter/decluttarr#194)
hi @Dark3clipse , apologies for the radio silence on my part.
I've been refactoring the entire application, and it took me way longer than I hoped.
Goal was to make it more maintainable, and also support multiple instances and some of the features people have been requesting - such as the obsolete tag of yours.
It's still in draft, and particularly the readme I still have to write (and I'm sure there's plenty of bugs).
But if you have any feedback / suggestions, I'd be happy to hear and also contributions are highly welcome:
Branch is here: https://github.com/ManiMatter/decluttarr/tree/decluttarr-v2
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.￼Message ID: ***@***.***>

2025-04-26 17:35 UTC, Dark3clipse commented
Hi @ManiMatter, could you make a PR for your rewrite such that I can do a review? Thank you

2025-05-19 18:58 UTC, ManiMatter commented
Hey @Dark3clipse 

apologies for my delay in responding.

The obsolete-feature is built into v2 already, thus don't think we'll need to rebase this code into v2.
Please check out https://github.com/ManiMatter/decluttarr/tree/decluttarr-v2

V2 is still in beta (full code refactoring) but apprecaite any feedback / bugs you may spot. 
Also VERY appreciative of any bug fix PRs directly against that branch.

Docker: Pull decluttarr:decluttarr-v2

2025-06-02 21:49 UTC, Dark3clipse commented
Hey @ManiMatter 

You can find my review here: https://github.com/Dark3clipse/decluttarr/pull/1#pullrequestreview-2889918616
I'm about halfway through, will continue soon.

2025-06-14 08:40 UTC, ManiMatter commented
Hi @Dark3clipse 
I will close this PR for now, as this feature is available in v2.

Looking forward to any further review comments, PRs!

2025-06-14 08:40 UTC, closed without merging

2026-04-21 22:18 UTC, ManiMatter commented
hi @Dark3clipse  - I am looking for maintainers / contributors who will help drive decluttarr further. 
Unfortunately, I have become the bottleneck and I won't have much time to spend on this any further. 

There are already a few promising PRs lined up that people created, and I am hoping that if we find maintainers, they can review these PRs and decide on whether to merge then / what else is needed on them.

Since in the past you were fabulous with your contribution, I wanted to check with you if you'd be willing to step up and become a formal maintainer for decluttarr?

2026-04-28 13:44 UTC, Dark3clipse commented
Hi @ManiMatter, thank you for reaching out to me. I would be willing to be a formal maintainer for decluttarr. It will be my first open-source project that I adopt, :) I would prefer it though if there would also be other maintainers as well.

2026-04-28 15:38 UTC, ManiMatter commented
Absolutely awesome. There are two other people who have raised their hand to become contributors and I send the invite to them. Anyone else coming forward, will also add them. 

I just sent you the invite as well. I suggest we exchange via https://github.com/ManiMatter/decluttarr/discussions/345 on what to prioritize next; if you have any time, I think it would be awesome if you could have a look into some of the open PRs, for instance the one adding in a UI (https://github.com/ManiMatter/decluttarr/pull/337). Feel free to completely own it; ie. review / amend together with the PR owner and once you think things are OK - let's merge.

Ps: also feel free to close/decline PRs if you feel they dont make sense or tag me if you want a second opinion and we discuss them there